2024-02-21 01:07:50.325 | INFO     | __main__:__create_log_file:46 - /app/ubuntu/app/src/logs/server_yolo_analys_log/runtime_server_yolo_analys_2024-2-21-1-7-50.log
2024-02-21 01:07:50.325 | INFO     | __main__:start:112 - Start server_yolo_analys
2024-02-21 01:08:14.667 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o52, 1]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 1
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f292c4dd650>
    │    │    │         └ JavaObject id=o52
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:16.744 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o52, 1]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 1
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f292c4dd650>
    │    │    │         └ JavaObject id=o52
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:17.693 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o52, 1]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 1
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f292c4dd650>
    │    │    │         └ JavaObject id=o52
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:18.501 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o57, 2]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 2
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f2a02e0d210>
    │    │    │         └ JavaObject id=o57
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:18.610 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o57, 2]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 2
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f2a02e0d210>
    │    │    │         └ JavaObject id=o57
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:18.737 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o57, 2]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 2
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f2a02e0d210>
    │    │    │         └ JavaObject id=o57
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:19.526 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o57, 2]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 2
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f2a02e0d210>
    │    │    │         └ JavaObject id=o57
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:19.637 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o57, 2]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 2
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f2a02e0d210>
    │    │    │         └ JavaObject id=o57
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:19.740 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o57, 2]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 2
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f2a02e0d210>
    │    │    │         └ JavaObject id=o57
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:19.839 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o57, 2]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 2
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f2a02e0d210>
    │    │    │         └ JavaObject id=o57
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:19.942 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o57, 2]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 2
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f2a02e0d210>
    │    │    │         └ JavaObject id=o57
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:20.762 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o62, 3]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 3
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f292c4c7f10>
    │    │    │         └ JavaObject id=o62
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:20.889 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o62, 3]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 3
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f292c4c7f10>
    │    │    │         └ JavaObject id=o62
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:21.033 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o62, 3]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 3
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f292c4c7f10>
    │    │    │         └ JavaObject id=o62
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:21.417 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o67, 4]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 4
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f2a02e40490>
    │    │    │         └ JavaObject id=o67
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:23.019 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o72, 5]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 5
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f292bbd9f10>
    │    │    │         └ JavaObject id=o72
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:23.780 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o77, 6]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 6
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f292bbf8950>
    │    │    │         └ JavaObject id=o77
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:23.927 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o77, 6]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 6
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f292bbf8950>
    │    │    │         └ JavaObject id=o77
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
2024-02-21 01:08:36.894 | INFO     | asyncio.events:_run:80 - An error has been caught in function '_run', process 'MainProcess' (5019), thread 'MainThread' (139818881200128):
Traceback (most recent call last):

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 121, in <module>
    run(sya.start())
    │   │   └ <function server_yolo_analys.start at 0x7f2918457560>
    │   └ <__main__.server_yolo_analys object at 0x7f2918447310>
    └ <function run at 0x7f2a1e672b60>

  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object server_yolo_analys.start at 0x7f2a02e60140>
           │      └ <function Runner.run at 0x7f2a1e0153a0>
           └ <asyncio.runners.Runner object at 0x7f29189d58d0>
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<server_yolo_analys.start() running at /usr/local/lib/python3.11/dist-packages/loguru/_logge...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x7f2a1e012fc0>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7f29189d58d0>
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f2a1e012f20>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f2a1e014d60>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f2a1e673380>
    └ <Handle <TaskStepMethWrapper object at 0x7f2a0a78b670>()>
> File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f2a0a78b670>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f2a0a78b670>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f2a0a78b670>()>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 117, in start
    query.awaitTermination()
    │     └ <function StreamingQuery.awaitTermination at 0x7f291850bc40>
    └ <pyspark.sql.streaming.query.StreamingQuery object at 0x7f292c4c6f90>

  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
           │    └ JavaObject id=o46
           └ <pyspark.sql.streaming.query.StreamingQuery object at 0x7f292c4c6f90>
  File "/usr/local/lib/python3.11/dist-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   └ <function capture_sql_exception.<locals>.deco at 0x7f292bba2840>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
    return f(*a, **kw)
           │  │    └ {}
           │  └ ('x', <py4j.clientserver.JavaClient object at 0x7f292f591f10>, 'o46', 'awaitTermination')
           └ <function get_return_value at 0x7f29189f22a0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/protocol.py", line 334, in get_return_value
    raise Py4JError(
          └ <class 'py4j.protocol.Py4JError'>

py4j.protocol.Py4JError: An error occurred while calling o46.awaitTermination
2024-02-21 01:08:36.900 | INFO     | __main__:__exit__:50 - End work server_yolo_analys
2024-02-21 01:08:37.027 | INFO     | __main__:__analys_frame:105 - An error has been caught in function '__analys_frame', process 'MainProcess' (5019), thread 'Thread-4 (run)' (139814438417984):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a1e8a1d00>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a1e8a19e0>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4 (run), started daemon 139814438417984)>
    │    └ <bound method ClientServerConnection.run of <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>>
    └ <Thread(Thread-4 (run), started daemon 139814438417984)>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 497, in run
    self.wait_for_commands()
    │    └ <function ClientServerConnection.wait_for_commands at 0x7f291872f060>
    └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 581, in wait_for_commands
    return_message = self._call_proxy(obj_id, self.stream)
                     │    │           │       │    └ <_io.BufferedReader name=46>
                     │    │           │       └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
                     │    │           └ 'p0'
                     │    └ <function ClientServerConnection._call_proxy at 0x7f291872f100>
                     └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                           │    │    │        │        └ [JavaObject id=o82, 7]
                           │    │    │        └ 'call'
                           │    │    └ 'p0'
                           │    └ <py4j.java_gateway.PythonProxyPool object at 0x7f291a1e8890>
                           └ <py4j.clientserver.ClientServerConnection object at 0x7f292c4c79d0>
  File "/usr/local/lib/python3.11/dist-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
    │    │    │         │    │                     └ 7
    │    │    │         │    └ <pyspark.sql.session.SparkSession object at 0x7f292bbfb710>
    │    │    │         └ JavaObject id=o82
    │    │    └ <class 'pyspark.sql.dataframe.DataFrame'>
    │    └ <bound method server_yolo_analys.__analys_frame of <__main__.server_yolo_analys object at 0x7f2918447310>>
    └ <pyspark.sql.utils.ForeachBatchFunction object at 0x7f2a02fa6c90>

> File "/app/ubuntu/app/src/server_yolo_analys.py", line 105, in __analys_frame
    self.__picture_recognition(url, m.unpackb(self.__redis.get(url)))
    │                          │    │ │       │                └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    │                          │    │ │       └ <__main__.server_yolo_analys object at 0x7f2918447310>
    │                          │    │ └ <function unpackb at 0x7f29f4b22660>
    │                          │    └ <module 'msgpack_numpy' from '/usr/local/lib/python3.11/dist-packages/msgpack_numpy.py'>
    │                          └ 'http://211.132.61.124:80/mjpg/video.mjpg'
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

  File "/app/ubuntu/app/src/server_yolo_analys.py", line 85, in __picture_recognition
    self.__producer.set("processed_images", value=f"{url}_redy".encode("utf-8"))
    └ <__main__.server_yolo_analys object at 0x7f2918447310>

AttributeError: 'cimpl.Producer' object has no attribute 'set'
